main:
  - name: Home
    url: '#about'
    weight: 10

  - name: Research
    url: '#featured'
    weight: 20

  - name: Publications
    url: '#publications'
    weight: 30

  - name: Database
    url: '#database'
    weight: 40
