main:
  - name: Home
    url: '#about'
    weight: 10

  - name: Research
    url: '#featured'
    weight: 20

  - name: Publications  # <--- 确保这里叫 Publications
    url: '#publications'
    weight: 30

  - name: Database
    url: 'https://github.com/hegu2692/KICDB' # 指向你的数据库
    weight: 40
