main:
  - name: Home
    url: '/'
    weight: 10

  - name: Research
    url: '/research/' # 跳转到独立的研究介绍页
    weight: 20

  - name: Publications
    url: '/publication/' # 跳转到独立的论文列表页
    weight: 30

  - name: Database
    url: '/database/' # 跳转到你刚才建立的数据库页
    weight: 40

  - name: Contact
    url: '/contact/' # 跳转到独立的联系方式页
    weight: 50
