main:
  - name: Home
    url: '/' # 点击回到主页
    weight: 10

  - name: Research
    url: '/' # 研究方向目前在主页上，所以指向主页
    weight: 20

  - name: Publications
    url: '/publication/' # <--- 关键修改：点击后进入独立的论文列表页面
    weight: 30

  - name: Database
    url: '/database/'
    weight: 40
