# -----------------------------------------------------------------------------
# Contact Details
# -----------------------------------------------------------------------------

# These details are used in the Contact widget.
email: 'dr.jian.zhang.phd at gmail.com'


# Your address
address:
  street: '628 Zhenyuan Rd, Guangming District'
  city: 'Shenzhen'
  region: 'Guangdong'
  postcode: '518107'
  country: 'China'
  country_code: 'CN'

# Geographic coordinates (for the map)
coordinates:
  latitude: '22.788'
  longitude: '113.924'
